HTML CSS_Homework_Gayathri
HackYourFuture-CPH/class30-homework pull request #4
Opened 2024-10-31 15:49 UTC by GayathriVenkatraman

2024-11-03 18:06 UTC, Khandohii requested changes
Well done @GayathriVenkatraman 👍 
Left a few comments 😊

2024-11-03 18:06 UTC, Khandohii commented on html-css/week1/styles.css
Please, try to keep your code clean and aligned, without unnecessary line breaks for better readability and scalability. 
The extension "Prettier" for VSCode helps a lot with this 👍

2024-11-05 09:16 UTC, GayathriVenkatraman commented on html-css/week1/index.html
> +                <button type="button"><a href="https://www.freecodecamp.org/learn/2022/responsive-web-design/build-a-survey-form-project/build-a-survey-form">View FCC Survey Form</a></button>
Okay

2024-11-05 09:39 UTC, GayathriVenkatraman commented on html-css/week1/styles.css
Thanks, this is really useful

2024-11-05 09:40 UTC, GayathriVenkatraman commented on html-css/week1/styles.css
> +    width: 2020px;
Done

2024-11-05 19:08 UTC, GayathriVenkatraman commented on html-css/week1/styles.css
media queries added

2024-11-05 21:29 UTC, Khandohii commented on html-css/week1/styles.css
I can't see commits with last updates in this PR.

2024-11-06 08:39 UTC, GayathriVenkatraman commented on html-css/week1/styles.css
I have been working on these comments in my local repository. I will update them here as well.

2024-11-06 10:40 UTC, merged