Javascript javascript1 week1/farzaneh
HackYourFuture-CPH/class30-homework pull request #58
Opened 2024-11-11 19:12 UTC by FarzanehAhmadi

2024-11-16 06:48 UTC, LucasIversen requested changes
Really like your solution of Housey pricey! 

Only need a few changes, and we're good 👍

2024-11-16 06:48 UTC, LucasIversen commented on javascript/javascript1/week1/Age-ify.js
> +console.log("You will be "+ age +" years old in " +yearFuture +"!");
Goood 👍

2024-11-16 06:48 UTC, LucasIversen commented on javascript/javascript1/week1/Ez-Namey.js
> +let startupName = firstWords[Math.floor(Math.random() * 10)] +" "+secondWords[Math.floor(Math.random() * 10)];
we could put the random numbers in their own variables.. Also, we can make the startupName a const since we're not gonna change it 👍

2024-11-16 06:48 UTC, LucasIversen commented on javascript/javascript1/week1/Goodboy-Oldboy.js
> +let shouldShowResultInDogYears = true;
This can be a const

2024-11-16 06:48 UTC, LucasIversen commented on javascript/javascript1/week1/Goodboy-Oldboy.js
> +if(shouldShowResultInDogYears==true){
Remember, in javascript we like to use `===` rather than `==` when comparing two values 😃

2024-11-16 06:48 UTC, LucasIversen commented on javascript/javascript1/week1/Housey-pricey.js
> +const peterHouse = {
Uuuuh!! Nice Farzaneh!

2024-11-17 23:30 UTC, FarzanehAhmadi commented on javascript/javascript1/week1/Housey-pricey.js
> +const peterHouse = {
Thank you for your valuable feedback; I’ve applied the changes!

2024-11-18 15:35 UTC, closed without merging