html-css/jianxin
HackYourFuture-CPH/class30-homework pull request #9
Opened 2024-11-01 09:18 UTC by jianxinz233

2024-11-03 18:31 UTC, Khandohii requested changes
Well done @jianxinz233 :clap:
Left a few comments to fix

2024-11-03 18:31 UTC, Khandohii commented on html-css/week1/index.html
> +                    <img id="projectimg" alt="surveyformimg" src="project02-mobile.jpg">
Remove a dublicate of id `id="projectimg"` on the page

2024-11-03 18:31 UTC, Khandohii commented on html-css/week1/index.html
Using `<header>` is best for marking the top section of your page, like the logo, title, or main navigation. It improves page structure and helps search engines understand your content better. It’s generally recommended to use `<header>` once per page to keep things simple and clear.

In the other place of the page you can change tag `<header>` by `<h2>`, `<h3>` or `<div>` and style it by class selector in css.

2024-11-03 18:31 UTC, Khandohii commented on html-css/week1/styles.css
It’s better to use class selectors over ID selectors for styling because classes are more flexible and reusable. Unlike IDs, which should be unique to each element, classes can be applied to multiple elements, making your CSS more efficient and easier to maintain.

2024-11-03 18:31 UTC, Khandohii commented on html-css/week1/styles.css
There are some issues with displaying content on mobile devices:

![image](https://github.com/user-attachments/assets/e22775fb-bf89-432b-ae9b-51c4ab0f57ca)

Fixing the height of blocks has a negative effect on the display of content, especially if the content is dynamic. Advice: do not use a fixed height for blocks with text, or style it by hiding excess text with the ability to display it when necessary.

2024-11-05 21:21 UTC, Khandohii approved these changes
Well Done @jianxinz233 👍 

I approve these changes, and leave a small tip for responsive view.

The block looks too compressed, doesn't it? Maybe it would be better to make it into one column per row or reduce the margins?
![image](https://github.com/user-attachments/assets/dc7dae3a-3168-4b62-9c46-84523be8bf74)

2024-11-05 21:53 UTC, jianxinz233 commented
@Khandohii Thank you so much! About the block, I have tried to make it become one row with CSS“ grid-template-columns: 1fr;” to adapt to mobile width. But I don’t know why it didn’t work 😅
And can I know what browser is in the screenshot that can check about media version? Thanks!

2024-11-06 09:46 UTC, jianxinz233 commented
> > @Khandohii Thank you so much! About the block, I have tried to make it become one row with CSS“ grid-template-columns: 1fr;” to adapt to mobile width. But I don’t know why it didn’t work 😅 And can I know what browser is in the screenshot that can check about media version? Thanks!
> 
> You're welcome 😊 It's the Google Chrome browser, to open inspector just press "F12", and then Ctrl+Shift+M to toggle device toolbar.
> 
> I see it works well with `grid-template-columns: 1fr;`, try to put it in right media query to make it work in the mobile view. ![image](https://private-user-images.githubusercontent.com/30953108/383343170-6d2c3606-3b98-410e-bef8-b726c1abf1d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4ODU0MDAsIm5iZiI6MTczMDg4NTEwMCwicGF0aCI6Ii8zMDk1MzEwOC8zODMzNDMxNzAtNmQyYzM2MDYtM2I5OC00MTBlLWJlZjgtYjcyNmMxYWJmMWQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDA5MjUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhNzhmMmM5ODhmODQ0MWEzNWYwYzA1YmViZmQxZTk2N2E2NDEyMWZlNjk4YTc5ZjVmZDJlN2M0OTI3YmZjNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xSxFG4H4bkpMPYUflczIrBf5hebDoTyTLhEd4huRmKI)

@Khandohii Thank you for your reply. And finally I found the problem, it was the misspelling of class name "project-box", I typed "projects-box" for responsive view 😂 I will go to fix it.

2024-11-06 21:30 UTC, Khandohii commented
> > > @Khandohii Thank you so much! About the block, I have tried to make it become one row with CSS“ grid-template-columns: 1fr;” to adapt to mobile width. But I don’t know why it didn’t work 😅 And can I know what browser is in the screenshot that can check about media version? Thanks!
> > 
> > 
> > You're welcome 😊 It's the Google Chrome browser, to open inspector just press "F12", and then Ctrl+Shift+M to toggle device toolbar.
> > I see it works well with `grid-template-columns: 1fr;`, try to put it in right media query to make it work in the mobile view. ![image](https://private-user-images.githubusercontent.com/30953108/383343170-6d2c3606-3b98-410e-bef8-b726c1abf1d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4ODU0MDAsIm5iZiI6MTczMDg4NTEwMCwicGF0aCI6Ii8zMDk1MzEwOC8zODMzNDMxNzAtNmQyYzM2MDYtM2I5OC00MTBlLWJlZjgtYjcyNmMxYWJmMWQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDA5MjUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhNzhmMmM5ODhmODQ0MWEzNWYwYzA1YmViZmQxZTk2N2E2NDEyMWZlNjk4YTc5ZjVmZDJlN2M0OTI3YmZjNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xSxFG4H4bkpMPYUflczIrBf5hebDoTyTLhEd4huRmKI)
> 
> @Khandohii Thank you for your reply. And finally I found the problem, it was the misspelling of class name "project-box", I typed "projects-box" for responsive view 😂 I will go to fix it.

Good job @jianxinz233 
Now you can merge this branch

2024-11-07 11:01 UTC, merged